apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board-front
  template:
    metadata:
      labels:
        app: board-front
    spec:
      containers:
        - name: board-front
          image: kudongku/board-front-image
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: board-front-service
spec:
  selector:
    app: board-front
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
